# Generated by Django 5.0.4 on 2024-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apelido'),
        ),
    ]
