# Generated by Django 5.0.4 on 2024-07-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizera', '0002_relatorio_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='numero_telefone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='mizera.numerotelefone'),
        ),
    ]
