# Generated by Django 5.0.4 on 2024-07-07 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizera', '0003_relatorio_numero_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='numero_telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mizera.numerotelefone'),
        ),
    ]
