# Generated by Django 5.0.4 on 2024-07-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mizera', '0004_alter_relatorio_numero_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='numero_telefone',
        ),
    ]
