# Generated by Django 5.0.4 on 2024-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizera', '0007_alter_relatorio_numero_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='apelido',
        ),
        migrations.AddField(
            model_name='numerotelefone',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='numerotelefone',
            name='numero',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
