# Generated by Django 5.0.4 on 2024-07-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizera', '0009_remove_numerotelefone_apelido_relatorio_apelido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerotelefone',
            name='numero',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
